# Generated by Django 3.2.11 on 2022-02-06 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(null=True, upload_to='audio')),
                ('data', models.BinaryField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voice_identification.student')),
            ],
        ),
    ]
