# Generated by Django 3.2.11 on 2022-02-07 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voice_identification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceVector',
            fields=[
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='voice_identification.student')),
                ('vector', models.BinaryField()),
            ],
        ),
    ]
