# Generated by Django 3.2.11 on 2022-02-08 02:42

from django.db import migrations, models
import voice_identification.models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_identification', '0004_alter_voicevector_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicedata',
            name='audio',
            field=models.FileField(null=True, upload_to=voice_identification.models.get_path),
        ),
    ]
